name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build executable
      run: pyinstaller --onefile mock_api.py

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: mock_api_exe
        path: dist/mock_api.exe

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: mock_api_exe
        path: ./dist

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/mock_api.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}